<?php
	require("../includes/helper.php");
	require("../includes/admin_functions.php");
	if (empty($_SESSION['id'])) {	
		if ($_SERVER["REQUEST_METHOD"] == "GET")
			render("register_form.php", ["title"=>"Register"]);
		elseif ($_SERVER["REQUEST_METHOD"] == "POST")
		{
			if (empty($_POST["user"]) || empty($_POST["password"]) || empty($_POST["confirm"] || empty($_POST["email"]))) { 
				render("register_form.php", ["message"=>"Please complete all fields"]);
			}
			elseif ($_POST["password"] != $_POST["confirm"]) {
				render("register_form.php", ["message"=>"Passwords do not match. Please try again"]);
			}
			// check if password has at least an uppercase, a digit, and is 6 characters long
			elseif ((strlen($_POST["password"])) < 6) {
				render("register_form.php", ["message"=>"Password needs to have at least 6 characters"]);
			}
			elseif (!(preg_match('~[A-Z]~', $_POST["password"])) ||
					!(preg_match('~\d~', $_POST["password"]))) {
				render("register_form.php", ["message"=>"Your password must include at least one uppercase and one digit"]);
			}
			// check that a valid email is entered, unnecessary?
			elseif (!filter_var($_POST["email"], FILTER_VALIDATE_EMAIL)) {
				render("register_form.php", ["message"=>"Please enter a valid email"]);
			}
			else
			{
				$user_db = $_POST["user"];
				$pw_db = password_hash($_POST["password"], PASSWORD_DEFAULT);
				$email = $_POST["email"];
				// confirmation code generated by a random number for activation
				$confirm_code = rand();
	
				// check if username already exists
				if (user_exists($user_db) == 1) 
					render("register_form.php", ["message"=>"Username already exists."]);
	
				// check if email already exists
				if (email_exists($email))
					render("register_form.php", ["message"=>"Email already in use."]);
	
				add_user($user_db, $email, $pw_db, $confirm_code);
	
				// Send email message to user for account activation
					// ideally would require full domain name but using server ip address
				$msg = "Confirm Your Email
						Click the link below to verify your account
						http://192.168.99.100:8088/public/activate.php?username=$user_db&code=$confirm_code";
			
				// requires "mail(<email address>, <subject title>, <msg>, <sender/src email>)" function
					// may require an actual web server in order to send the emails
				mail($email, "Verify Your Email on Camagru", $msg, "From: donotreply@camagru.com");
			
				// will need to pass registeration values & render the button click to an "register complete" page 
				render("success.php", ["message"=>"Registration Complete! Please activate your account through the email provided."]);
			}
		}
	}
	render("error.php");
?>
